name: Publish Quarto Site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish
        run: |
          quarto render
          quarto publish
        env:
          QUARTO_PUBLISH_TOKEN: ${{ secrets.QUARTO_PUBLISH_TOKEN }}