name: Render and Publish Quarto

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore R Dependencies
        run: |
          Rscript -e "install.packages('renv')"
          Rscript -e "renv::restore()"

      - name: Install Required R Packages
        run: |
          Rscript -e "install.packages('rmarkdown')"
          Rscript -e "install.packages('knitr')"

      - name: Render Quarto Project
        run: quarto render